export const OPEN_MODAL_PULL_IMAGE = "OPEN_MODAL_PULL_IMAGE";
export const CLOSE_MODAL_PULL_IMAGE = "CLOSE_MODAL_PULL_IMAGE";

export const OPEN_MODAL_RUN_IMAGE = "OPEN_MODAL_RUN_IMAGE";
export const CLOSE_MODAL_RUN_IMAGE = "CLOSE_MODAL_RUN_IMAGE";

export const GET_LIST_IMAGE_IN_DEVICE = "GET_LIST_IMAGE_IN_DEVICE";
export const GET_LIST_IMAGE_IN_DEVICE_SUCCESS =
  "GET_LIST_IMAGE_IN_DEVICE_SUCCESS";
export const GET_LIST_IMAGE_IN_DEVICE_FAIL = "GET_LIST_IMAGE_IN_DEVICE_FAIL";

export const GET_LIST_CONTAINER_IN_DEVICE = "GET_LIST_CONTAINER_IN_DEVICE";
export const GET_LIST_CONTAINER_IN_DEVICE_SUCCESS =
  "GET_LIST_CONTAINER_IN_DEVICE_SUCCESS";
export const GET_LIST_CONTAINER_IN_DEVICE_FAIL =
  "GET_LIST_CONTAINER_IN_DEVICE_FAIL";

export const PULL_IMAGE = "PULL_IMAGE";
export const PULL_IMAGE_SUCCESS = "PULL_IMAGE_SUCCESS";
export const PULL_IMAGE_FAIL = "PULL_IMAGE_FAIL";
export const PULL_IMAGE_PENDING = "PULL_IMAGE_PENDING";

export const GET_DEVICE_IMAGE_BY_ID = "GET_DEVICE_IMAGE_BY_ID";

export const RUN_IMAGE_DEVICE = "RUN_IMAGE_DEVICE";
export const RUN_IMAGE_DEVICE_SUCCESS = "RUN_IMAGE_DEVICE_SUCCESS";
export const RUN_IMAGE_DEVICE_FAIL = "RUN_IMAGE_DEVICE_FAIL";
export const RUN_IMAGE_DEVICE_PENDING = "RUN_IMAGE_DEVICE_PENDING";

export const GET_DEVICE_CONTAINER_BY_ID_3 = "GET_DEVICE_CONTAINER_BY_ID_3";
export const GET_DEVICE_CONTAINER_BY_ID_1 = "GET_DEVICE_CONTAINER_BY_ID_1";
export const GET_DEVICE_CONTAINER_BY_ID_2 = "GET_DEVICE_CONTAINER_BY_ID_2";

export const START_CONTAINER = "START_CONTAINER";
export const START_CONTAINER_SUCCESS = "START_CONTAINER_SUCCESS";
export const START_CONTAINER_FAIL = "START_CONTAINER_FAIL";
export const START_CONTAINER_PENDING = "START_CONTAINER_PENDING";

export const STOP_CONTAINER = "STOP_CONTAINER";
export const STOP_CONTAINER_SUCCESS = "STOP_CONTAINER_SUCCESS";
export const STOP_CONTAINER_FAIL = "STOP_CONTAINER_FAIL";
export const STOP_CONTAINER_PENDING = "STOP_CONTAINER_PENDING";
