export const OPEN_MODAL_PULL_IMAGE = "OPEN_MODAL_PULL_IMAGE";
export const CLOSE_MODAL_PULL_IMAGE = "CLOSE_MODAL_PULL_IMAGE";

export const OPEN_MODAL_RUN_IMAGE = "OPEN_MODAL_RUN_IMAGE";
export const CLOSE_MODAL_RUN_IMAGE = "CLOSE_MODAL_RUN_IMAGE";

export const GET_LIST_IMAGE_IN_DEVICE = "GET_LIST_IMAGE_IN_DEVICE";
export const GET_LIST_IMAGE_IN_DEVICE_SUCCESS =
  "GET_LIST_IMAGE_IN_DEVICE_SUCCESS";
export const GET_LIST_IMAGE_IN_DEVICE_FAIL = "GET_LIST_IMAGE_IN_DEVICE_FAIL";

export const GET_LIST_CONTAINER_IN_DEVICE = "GET_LIST_CONTAINER_IN_DEVICE";
export const GET_LIST_CONTAINER_IN_DEVICE_SUCCESS =
  "GET_LIST_CONTAINER_IN_DEVICE_SUCCESS";
export const GET_LIST_CONTAINER_IN_DEVICE_FAIL =
  "GET_LIST_CONTAINER_IN_DEVICE_FAIL";

export const PULL_IMAGE = "PULL_IMAGE";
export const PULL_IMAGE_SUCCESS = "PULL_IMAGE_SUCCESS";
export const PULL_IMAGE_FAIL = "PULL_IMAGE_FAIL";
export const PULL_IMAGE_PENDING = "PULL_IMAGE_PENDING";

export const GET_DEVICE_IMAGE_BY_ID = "GET_DEVICE_IMAGE_BY_ID";

export const RUN_IMAGE_DEVICE = "RUN_IMAGE_DEVICE";
export const RUN_IMAGE_DEVICE_SUCCESS = "RUN_IMAGE_DEVICE_SUCCESS";
export const RUN_IMAGE_DEVICE_FAIL = "RUN_IMAGE_DEVICE_FAIL";
export const RUN_IMAGE_DEVICE_PENDING = "RUN_CONTAINER_DEVICE_PENDING";

export const GET_DEVICE_CONTAINER_BY_ID = "GET_DEVICE_CONTAINER_BY_ID";
