export const GET_LIST_DOCKER_HUB_IMAGE = "GET_LIST_DOCKER_HUB_IMAGE";
export const GET_LIST_DOCKER_HUB_IMAGE_SUCCESS =
  "GET_LIST_DOCKER_HUB_IMAGE_SUCCESS";
export const GET_LIST_DOCKER_HUB_IMAGE_FAIL = "GET_LIST_DOCKER_HUB_IMAGE_FAIL";

export const OPEN_MODAL_PUSH_IMAGE = "OPEN_MODAL_PUSH_IMAGE";
export const CLOSE_MODAL_PUSH_IMAGE = "CLOSE_MODAL_PUSH_IMAGE";

export const PUSH_IMAGE = "PUSH_IMAGE";
export const PUSH_IMAGE_SUCCESS = "PUSH_IMAGE_SUCCESS";
export const PUSH_IMAGE_FAIL = "PUSH_IMAGE_FAIL";
export const PUSH_IMAGE_PENDING = "PUSH_IMAGE_PENDING";

export const GET_DH_IMAGE_BY_ID = "GET_DH_IMAGE_BY_ID";
