export const GET_LIST_LOCAL_IMAGE = "GET_LIST_LOCAL_IMAGE";
export const GET_LIST_LOCAL_IMAGE_SUCCESS = "GET_LIST_LOCAL_IMAGE_SUCCESS";
export const GET_LIST_LOCAL_IMAGE_FAIL = "GET_LIST_LOCAL_IMAGE_FAIL";
