export const GET_LIST_LOCAL_IMAGE = "GET_LIST_LOCAL_IMAGE";
export const GET_LIST_LOCAL_IMAGE_SUCCESS = "GET_LIST_LOCAL_IMAGE_SUCCESS";
export const GET_LIST_LOCAL_IMAGE_FAIL = "GET_LIST_LOCAL_IMAGE_FAIL";

export const OPEN_MODAL_BUILD_IMAGE = "OPEN_MODAL_BUILD_IMAGE";
export const CLOSE_MODAL_BUILD_IMAGE = "CLOSE_MODAL_BUILD_IMAGE";

export const BUILD_IMAGE = "BUILD_IMAGE";
export const BUILD_IMAGE_SUCCESS = "BUILD_IMAGE_SUCCESS";
export const BUILD_IMAGE_FAIL = "BUILD_IMAGE_FAIL";
export const BUILD_IMAGE_PENDING = "BUILD_IMAGE_PENDING";

export const GET_IMAGE_BY_ID = "GET_IMAGE_BY_ID";
